language: r

r_github_packages:
 - hadley/devtools
 - jimhester/covr

after_success:
 - Rscript -e 'devtools::install()'
 - Rscript -e 'library(covr); coveralls(exclusion=list("R/benchmark.R" = 1, "R/RcppExports.R" = 1, "src/RcppExports.cpp" = 1))'
