language: r

sudo: required

warnings_are_errors: false

env: R_CHECK_CRAN_INCOMING_=FALSE

r_github_packages:
 - jimhester/covr
 - hadley/testthat

# debian package names: libxml2-dev libssl-dev r-base-core r-cran-xml r-cran-ggplot2 r-cran-rcurl r-cran-bitops r-cran-brew r-cran-rcolorbrewer r-cran-rcpp r-cran-dichromat r-cran-munsell r-cran-checkmate r-cran-evaluate r-cran-plyr r-cran-gtable r-cran-reshape2 r-cran-scales r-cran-proto r-cran-catools r-cran-testthat r-cran-memoise r-cran-digest r-cran-xtable
# at least some of the following don't have debian packages (at time of writing)
r_binary_packages:
 - devtools
 - XML
 - testthat
 - Rcpp
 - ggplot2
 - brew
 - rcolorbrewer
 - dichromat
 - munsell
 - checkmate
 - scales
 - proto
 - catools
 - evaluate
 - plyr
 - gtable
 - reshape2
 - knitr
 - microbenchmark
 - profr
 - xtable
 - magrittr
 - memoise
 - profr
 - digest
 - rmarkdown

after_success:
 - Rscript -e 'devtools::install()'
 - Rscript -e 'devtools::session_info()'
 - env: COVR=true
 - Rscript -e 'library(covr); coveralls(exclusions = list("R/RcppExports.R", "src/RcppExports.cpp", "R/benchmark.R", quiet = FALSE)'

notifications:
  email:
    on_success: change
    on_failure: change
