# https://docs.travis-ci.com/user/languages/r
language: r
sudo: false
cache: packages
r:
#  - oldrel # when oldrel = 3.1, there are S3 method problems I can't debug
  - release
  - devel

os:
  - linux
#  - osx

# compiler:
#   - gcc
#   - clang

matrix:
  allow_failures:
    - r: oldrel

repos:
  CRAN: https://cran.rstudio.com
# Rcpp: http://rcppcore.github.io/drat # github ahead and I need the github version

warnings_are_errors: true

# seperate lines seems to mean the whole build is repeated each line
env:
  - OMP_NUM_THREADS=4 R_CHECK_CRAN_INCOMING_=FALSE ICD_SLOW_TESTS=TRUE ICD_ONLINE_TESTS=FALSE _R_CHECK_FORCE_SUGGESTS_=FALSE
  - OMP_NUM_THREADS=1 R_CHECK_CRAN_INCOMING_=FALSE ICD_SLOW_TESTS=TRUE ICD_ONLINE_TESTS=FALSE _R_CHECK_FORCE_SUGGESTS_=FALSE

r_github_packages:
  - jimhester/covr
#  - hadley/testthat
#  - RcppCore/Rcpp

before_script:
 - ls -R
 - rm .Rinstignore  # install everything for testing
 - sed -i '/[Dd]ata/d' .Rbuildignore # do include data for testing

after_success:
# environment is copied forward from previous, so slow tests are on. Repeat anyway while not working!
# coverage does re-install the package (it needs to rebuild with debugging/coverage compilation), so there is potential to change .Rinstignore and .Rbuildignore
#  - export ICD_SLOW_TESTS=TRUE ICD_ONLINE_TESTS=FALSE
  - ls -R
  - cat ./icd.Rcheck/tests/test-all.Rout
  - Rscript -e 'library(covr); cov <- package_coverage(path = ".", quote(options(icd.do_slow_tests = TRUE)), quiet = FALSE, exclusions = list("inst/include/icd_RcppExports.h", "R/RcppExports.R", "src/RcppExports.cpp", "R/benchmark.R")); coveralls(cov)'
# do vignettes once regular coverage is working fully
# - Rscript -e 'library(covr); options(warn = -1);  package_coverage(type = "vignette", quiet = FALSE, exclusions = c("inst/include/icd_RcppExports.h", "R/generate_deprecated_data.R", "R/generate_mappings.R", "R/generate_sysdata.R"))'

notifications:
  email:
    on_success: change
    on_failure: change

