language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - travis_wait mvn install
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package jimhester/covr

script: travis_wait ./travis-tool.sh run_tests

after_success:
  - Rscript -e --verbose 'library(covr); coveralls()'

after_failure:
  - ./travis-tool.sh dump_logs

env:
  global:
    - R_CHECK_ARGS="--build-vignettes --as-cran --timings"
    - _R_CHECK_TIMINGS_="5"
# report timings for more than 5 seconds per test or example. Default with --as-cran is 10 seconds.
# tests are done by coveralls, maybe avoid doing twice?

#  - WARNINGS_ARE_ERRORS=1

notifications:
  email:
    on_success: change
    on_failure: change
