language: r

sudo: required

warnings_are_errors: false

env: R_CHECK_CRAN_INCOMING_=FALSE

r_github_packages:
 - jimhester/covr

after_success:
 - Rscript -e 'devtools::install()'
 - Rscript -e 'devtools::session_info()'
 - Rscript -e 'library(covr); coveralls(exclusions = list("R/RcppExports.R" = c(1,100000), "src/RcppExports.cpp" = c(1:100000), "R/benchmark.R" = c(1:100000)))'
