# https://docs.travis-ci.com/user/languages/r
language: R
cache: packages
r: devel

warnings_are_errors: true

# seperate lines seems to mean the whole build is repeated each line
env:
 - R_CHECK_CRAN_INCOMING_=FALSE ICD_SLOW_TESTS=TRUE ICD_ONLINE_TESTS=FALSE _R_CHECK_FORCE_SUGGESTS_=FALSE

# debian package names: libxml2-dev libssl-dev r-base-core r-cran-xml r-cran-ggplot2 r-cran-rcurl r-cran-bitops r-cran-brew r-cran-rcolorbrewer r-cran-rcpp r-cran-dichromat r-cran-munsell r-cran-checkmate r-cran-evaluate r-cran-plyr r-cran-gtable r-cran-reshape2 r-cran-scales r-cran-proto r-cran-catools r-cran-testthat r-cran-memoise r-cran-digest r-cran-xtable
# at least some of the following don't have debian packages (at time of writing)

r_github_packages:
 - jimhester/covr
 - hadley/testthat
 - RcppCore/Rcpp

after_success:
 # vignette coverage, don't submit to coveralls!
 - Rscript -e 'library(covr); package_coverage(type = "vignette", quiet = FALSE, exclusions = c("inst/include/icd_RcppExports.h", "R/generate_deprecated_data.R", "R/generate_mappings.R", "R/generate_sysdata.R"))'
 - Rscript -e 'library(covr); coveralls(type = "test", exclusions = list("inst/include/icd_RcppExports.h", "R/RcppExports.R", "src/RcppExports.cpp", "R/benchmark.R"), quiet = FALSE)'
 # or try travis_wait, but this seems not to report the results to coveralls
#  - travis_wait Rscript -e 'library(covr); coveralls(exclusions = list("inst/include/icd_RcppExports.h", "R/RcppExports.R", "src/RcppExports.cpp", "R/benchmark.R"), quiet = FALSE, type = "test")'

 # # doing codecov on wercker now:
 #- env: COVR=true
 #- Rscript -e 'library(covr); codecov(exclusions = list("inst/include/icd_RcppExports.h", "R/RcppExports.R", "src/RcppExports.cpp", "R/benchmark.R"), quiet = FALSE)'


notifications:
  email:
    on_success: change
    on_failure: change
