# https://docs.travis-ci.com/user/languages/r
language: r
dist: trusty
sudo: false
cache: packages

addons:
  apt:
    packages:
      r-cran-rodbc

r:
  - oldrel # when oldrel = 3.1, there are S3 method problems I can't debug
  - release
  - devel

matrix:
  allow_failures:
    - r: oldrel
    - os: osx

repos:
  CRAN: https://cloud.r-project.org

r_github_packages:
  - jimhester/covr

warnings_are_errors: true

# seperate lines seems to mean the whole build is repeated each line.
# As of 2013 at least, travis offers ~1.5 cores per process
env:
  - OMP_NUM_THREADS=1 CFLAGS="-O0 -Werror -Wall -Wextra -pedantic -Wno-unused-parameter -Wno-unused-variable" CXXFLAGS="-O0 -Werror -Wall -Wextra -pedantic -Wno-unused-parameter -Wno-unused-variable"
  - OMP_NUM_THREADS=2 CFLAGS="-O3 -march=native" CXXFLAGS="-O3 -march=native"

before_script:
 - ls -R
 - rm .Rinstignore  # do install everything for testing
 - sed -i.old '/[Dd]ata/d' .Rbuildignore # do include data for testing
 - export R_CHECK_CRAN_INCOMING_=FALSE
 - export ICD_SLOW_TESTS=TRUE
 - export _R_CHECK_FORCE_SUGGESTS_=FALSE

after_success:
# environment is copied forward from previous, so slow tests are on. Repeat anyway while not working!
# coverage does re-install the package (it needs to rebuild with debugging/coverage compilation), so there is potential to change .Rinstignore and .Rbuildignore
#  - export ICD_SLOW_TESTS=TRUE
#  - ls -R
  test-all-rout: cat ./icd.Rcheck/tests/test-all.Rout
  do-coveralls: >
    Rscript -e
      "options(warn = -1);
      line_exclusions = list(
      'inst/include/icd_RcppExports.h',
      'R/children_alt.R',
      'R/comorbid_alt.R',
      'R/parse-icd10cm-xml.R',
      'R/ranges_alt.R',
      'R/sort_alt.R',
      'src/convert_alt.cpp',
      'src/manip_alt.cpp',
      'src/ranges_alt.cpp',
      'R/fuzz.R');
      covr::coveralls(quiet = TRUE, line_exclusions = line_exclusions);
      covr::package_coverage(type = "vignette", quiet = TRUE, line_exclusions = line_exclusions)"

notifications:
  email:
    on_success: change
    on_failure: change
